# Generated by Django 5.2.3 on 2025-06-17 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='企業名')),
                ('industry', models.CharField(blank=True, max_length=100, verbose_name='業界')),
                ('description', models.TextField(blank=True, verbose_name='企業説明')),
            ],
        ),
    ]
