# Generated by Django 5.2.3 on 2025-06-17 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlySales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='年月')),
                ('value', models.FloatField(verbose_name='売上')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_sales', to='core.company')),
            ],
            options={
                'verbose_name': '月次売上',
                'verbose_name_plural': '月次売上一覧',
                'ordering': ['date'],
            },
        ),
    ]
