# Generated by Django 5.1.2 on 2025-06-24 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_monthlysales'),
    ]

    operations = [
        migrations.CreateModel(
            name='EdinetDocuments',
            fields=[
                ('doc_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('edinet_code', models.CharField(blank=True, max_length=10, null=True)),
                ('filer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('doc_type_code', models.CharField(blank=True, max_length=10, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('submit_datetime', models.DateTimeField(blank=True, null=True)),
                ('is_xbrl_parsed', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'edinet_documents',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='monthlysales',
            name='company',
        ),
        migrations.CreateModel(
            name='FinancialData',
            fields=[
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.edinetdocuments')),
                ('edinet_code', models.CharField(blank=True, max_length=10, null=True)),
                ('filer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('fiscal_year', models.IntegerField(blank=True, null=True)),
                ('net_assets', models.BigIntegerField(blank=True, null=True)),
                ('total_assets', models.BigIntegerField(blank=True, null=True)),
                ('net_sales', models.BigIntegerField(blank=True, null=True)),
                ('operating_income', models.BigIntegerField(blank=True, null=True)),
                ('ordinary_income', models.BigIntegerField(blank=True, null=True)),
                ('net_income', models.BigIntegerField(blank=True, null=True)),
                ('operating_cash_flow', models.BigIntegerField(blank=True, null=True)),
                ('r_and_d_expenses', models.BigIntegerField(blank=True, null=True)),
                ('number_of_employees', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'financial_data',
                'ordering': ['-fiscal_year'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FinancialDataValidated',
            fields=[
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.edinetdocuments')),
                ('edinet_code', models.CharField(max_length=10)),
                ('filer_name', models.CharField(max_length=255)),
                ('fiscal_year', models.IntegerField(blank=True, null=True)),
                ('net_assets', models.BigIntegerField()),
                ('total_assets', models.BigIntegerField()),
                ('net_sales', models.BigIntegerField()),
                ('operating_income', models.BigIntegerField()),
                ('ordinary_income', models.BigIntegerField()),
                ('net_income', models.BigIntegerField()),
                ('total_liabilities', models.BigIntegerField()),
                ('operating_cash_flow', models.BigIntegerField()),
                ('r_and_d_expenses', models.BigIntegerField()),
                ('number_of_employees', models.IntegerField()),
                ('confidence_score', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'financial_data_validated',
                'ordering': ['-fiscal_year'],
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='MonthlySales',
        ),
    ]
