# Generated by Django 5.1.2 on 2025-06-30 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_edinetdocuments_remove_monthlysales_company_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='学籍番号')),
                ('university', models.CharField(blank=True, max_length=100, null=True, verbose_name='大学名')),
                ('department', models.CharField(blank=True, max_length=100, null=True, verbose_name='学部・学科')),
                ('graduation_year', models.IntegerField(blank=True, null=True, verbose_name='卒業予定年')),
                ('interests', models.TextField(blank=True, null=True, verbose_name='興味のある業界・職種')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ユーザープロフィール',
                'verbose_name_plural': 'ユーザープロフィール',
            },
        ),
    ]
